= Quarkus OmniFaces extension
:page-layout: base
:source-language: java
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:numbered:
:doctype: book
:toc: preamble
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:


Enables OmniFaces in Quarkus applications

 
== How to try it?

This project depends on `MyFaces` and `Quarkus MyFaces` extension.

=== Build MyFaces 

* clone https://github.com/apache/myfaces.git 
* `mvn versions:set -DnewVersion=3.0.0-M1 -DprocessAllModules` (NOTE: we need to update the version to M1 as Quarkus does _NOT_ support snapshots)
* `mvn clean install -DskipTests`

=== Build quarkus-myfaces

* `git clone https://github.com/tandraschko/quarkus-myfaces && cd quarkus-myfaces/quarkus-myfaces && mvn clean install`
 
[TIP]
====

To build the quarkus extension you need to add jboss maven repository to your maven settings.xml:

----
<repositories>
    <repository>
        <id>jboss</id>
        <name>jboss repo</name>
        <url>https://repository.jboss.org/nexus/content/groups/public-jboss/</url>
    </repository>
</repositories>
<pluginRepositories>
    <pluginRepository>
        <id>jboss</id>
        <name>jboss repo</name>
        <url>https://repository.jboss.org/nexus/content/groups/public-jboss/</url>
   </pluginRepository>
</pluginRepositories>
----

====

=== Build OmniFaces

Currently this project depends on the trunk version of OmniFaces to be released as *v3.4*, follow the steps below to install it locally:

`git clone https://github.com/omnifaces/omnifaces && mvn versions:set -DnewVersion=3.4 && mvn clean install -DskipTests`


=== Build this project

`mvn clean package`


=== Run sample application

* `cd system-tests && mvn compile quarkus:dev`
* access http://localhost:8080/index.xhtml

TIP: Run via quarkus runner with `mvn clean package && java -jar target/quarkus-omnifaces-st-runner.jar.jar`

=== Run System tests

`mvn clean test`


=== Running Admin Starter application

Quarkus admin starter is a more elaborated application which uses omnifaces and quarkus myfaces extension. Follow the instructions on quarkus-admin-starter in order to run it.

