= Quarkus OmniFaces extension - This repo is not maintained anymore, go to: https://github.com/quarkiverse/quarkus-omnifaces
:page-layout: base
:source-language: java
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:numbered:
:doctype: book
:toc: preamble
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

image:https://github.com/adminfaces/quarkus-omnifaces/actions/workflows/ci.yml/badge.svg[Build Status, link=https://github.com/adminfaces/quarkus-omnifaces/actions/workflows/ci.yml]
image:https://img.shields.io/maven-central/v/com.github.adminfaces/quarkus-omnifaces.svg?label=Maven%20Central["Maven Central",link="https://search.maven.org/search?q=g:com.github.adminfaces%20AND%20a:quarkus-omnifaces"]


Enables OmniFaces in Quarkus applications

== How to try it?

Just add the following dependency:

[source, xml]
----
<dependency>
    <groupId>com.github.adminfaces</groupId>
    <artifactId>quarkus-omnifaces</artifactId>
    <version>1.4.0</version>
</dependency>
----

=== Run sample application

* `cd system-tests && mvn compile quarkus:dev`
* access http://localhost:8080/index.xhtml

TIP: Run via quarkus runner with `mvn clean package && java -jar system-tests/target/quarkus-app/quarkus-run.jar`

=== Native mode

To run o quarkus native use:

`mvn clean package -Pnative &&  ./system-tests/target/quarkus-app/quarkus-run`

=== Run System tests

`mvn clean test`

=== Run native tests

`mvn verify -Pnative`


=== Other examples

https://github.com/adminfaces/quarkus-admin-starter[Quarkus admin starter^] and https://github.com/adminfaces/quarkus-admin-showcase[Quarkus admin showcase^] are more elaborated applications using quarkus-omnifaces and quarkus myfaces extension. Follow the instructions on readme in order to run them.

