= Quarkus OmniFaces extension
:page-layout: base
:source-language: java
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:numbered:
:doctype: book
:toc: preamble
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:


Enables OmniFaces in Quarkus applications

 
== How to try it?

This project depends on `MyFaces` and `Quarkus MyFaces` extension.

=== Build MyFaces 

* clone https://github.com/apache/myfaces.git 
* `mvn versions:set -DnewVersion=3.0.0-SNAPSHOT -DprocessAllModules` (needed while myfaces 3.x is not released)
* `mvn clean install -DskipTests`

=== Build quarkus-myfaces

* `git clone https://github.com/tandraschko/quarkus-myfaces && cd quarkus-myfaces/quarkus-myfaces && mvn clean install`
 
[TIP]
====

To build the quarkus extension you need to add jboss maven repository to your maven settings.xml:

----
<repositories>
    <repository>
        <id>jboss</id>
        <name>jboss repo</name>
        <url>https://repository.jboss.org/nexus/content/groups/public-jboss/</url>
    </repository>
</repositories>
<pluginRepositories>
    <pluginRepository>
        <id>jboss</id>
        <name>jboss repo</name>
        <url>https://repository.jboss.org/nexus/content/groups/public-jboss/</url>
   </pluginRepository>
</pluginRepositories>
----

====


=== Install quarkus omnifaces

`mvn clean install`

=== Run sample application

* `cd system-tests && mvn compile quarkus:dev`
* access http://localhost:8080/index.xhtml

TIP: Run via quarkus runner with `mvn clean package && java -jar target/quarkus-omnifaces-st-runner.jar`

=== Run System tests

`mvn clean test`


=== Running Admin Starter application

https://github.com/adminfaces/quarkus-admin-starter[Quarkus admin starter^] and https://github.com/adminfaces/quarkus-admin-showcase[Quarkus admin showcase^] are more elaborated applications using quarkus-omnifaces and quarkus myfaces extension. Follow the instructions on quarkus-admin-starter in order to run it.

