= Quarkus OmniFaces extension
:page-layout: base
:source-language: java
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:numbered:
:doctype: book
:toc: preamble
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:


Enables OmniFaces in Quarkus applications

 
== How to try it?

This project depends on `MyFaces` and https://github.com/apache/myfaces/tree/master/extensions/quarkus[`Quarkus MyFaces` extension^].

=== Install quarkus omnifaces extension

On the root of this project run:

`mvn clean install -DskipTests`

[TIP]
====

To build the quarkus extension you need to add jboss maven repository to your maven settings.xml:

----
<repositories>
    <repository>
        <id>jboss</id>
        <name>jboss repo</name>
        <url>https://repository.jboss.org/nexus/content/groups/public-jboss/</url>
    </repository>
</repositories>
<pluginRepositories>
    <pluginRepository>
        <id>jboss</id>
        <name>jboss repo</name>
        <url>https://repository.jboss.org/nexus/content/groups/public-jboss/</url>
   </pluginRepository>
</pluginRepositories>
----

====

=== Run sample application

* `cd system-tests && mvn compile quarkus:dev`
* access http://localhost:8080/index.xhtml

TIP: Run via quarkus runner with `mvn clean package && java -jar target/quarkus-omnifaces-st-runner.jar`

=== Run System tests

`mvn clean test`


=== Other examples

https://github.com/adminfaces/quarkus-admin-starter[Quarkus admin starter^] and https://github.com/adminfaces/quarkus-admin-showcase[Quarkus admin showcase^] are more elaborated applications using quarkus-omnifaces and quarkus myfaces extension. Follow the instructions on readme in order to run them.

